﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace LinearRegression.MLModels
{
    public partial class WeatherMLModel
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(new []{new InputOutputColumnPair(@"Summary", @"Summary"),new InputOutputColumnPair(@"Precip Type", @"Precip Type")})      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"Humidity", @"Humidity"),new InputOutputColumnPair(@"Wind Speed (km/h)", @"Wind Speed (km/h)"),new InputOutputColumnPair(@"Wind Bearing (degrees)", @"Wind Bearing (degrees)"),new InputOutputColumnPair(@"Visibility (km)", @"Visibility (km)"),new InputOutputColumnPair(@"Pressure (millibars)", @"Pressure (millibars)")}))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Summary",@"Precip Type",@"Humidity",@"Wind Speed (km/h)",@"Wind Bearing (degrees)",@"Visibility (km)",@"Pressure (millibars)"}))      
                                    .Append(mlContext.Regression.Trainers.FastTree(new FastTreeRegressionTrainer.Options(){NumberOfLeaves=12,MinimumExampleCountPerLeaf=2,NumberOfTrees=56,MaximumBinCountPerFeature=1023,FeatureFraction=0.99999999,LearningRate=0.999999776672986,LabelColumnName=@"Temperature (C)",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
